### PR TITLE
Adapt raiden comma style

### PR DESCRIPTION
**Pull request by palango**

### CODE REVIEW

**Comment by LefterisJP** [comment]
Guys I would also suggest to have the exact same style/linting tools in all of the projects. As such you can put a linter for the commas (and also for some other issues). In raiden we got: 

```
flake8==3.6.0
flake8-bugbear==18.8.0
flake8-commas==2.0.0
flake8-tuple==0.2.13
isort==4.2.15
```

commans will find all of those, bugbear will find miscellaneous bugs and tuple will find commas that introduce tuples where you don't expect them

**Comment by karlb** [comment]
@LefterisJP: exactly these lines are part of this PR (only the isort version differs). Maybe we can start moving these parts to a shared place in the monorepo.

**Comment by LefterisJP** [comment]
@karlb oh my god I am blind. I looked at the diff to see if they were added and could not see them :)

**Comment by LefterisJP** [comment]
> Maybe we can start moving these parts to a shared place in the monorepo.

The monorepo will essentially be the client repo. But if we go with the original plan I guess each subproject needs its own requirements files anyway. Perhaps in the top directory there could be a tool that checks if the 3 subprojects have the same linting requirements -- but perhaps this is also an overkill.

**Pull request merged**
